apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: clusterpools.hive.openshift.io
spec:
  group: hive.openshift.io
  names:
    kind: ClusterPool
    listKind: ClusterPoolList
    plural: clusterpools
    shortNames:
    - cp
    singular: clusterpool
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ClusterPool represents a pool of clusters that should be kept ready
        to be given out to users. Clusters are removed from the pool once claimed
        and then automatically replaced with a new one.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ClusterPoolSpec defines the desired state of the ClusterPool.
          properties:
            baseDomain:
              description: BaseDomain is the base domain to use for all clusters created
                in this pool.
              type: string
            platform:
              description: Platform encompasses the desired platform for the cluster.
              properties:
                aws:
                  description: AWS is the configuration used when installing on AWS.
                  properties:
                    credentialsSecretRef:
                      description: CredentialsSecretRef refers to a secret that contains
                        the AWS account access credentials.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    region:
                      description: Region specifies the AWS region where the cluster
                        will be created.
                      type: string
                    userTags:
                      additionalProperties:
                        type: string
                      description: UserTags specifies additional tags for AWS resources
                        created for the cluster.
                      type: object
                  required:
                  - credentialsSecretRef
                  - region
                  type: object
                azure:
                  description: Azure is the configuration used when installing on
                    Azure.
                  properties:
                    baseDomainResourceGroupName:
                      description: BaseDomainResourceGroupName specifies the resource
                        group where the azure DNS zone for the base domain is found
                      type: string
                    credentialsSecretRef:
                      description: CredentialsSecretRef refers to a secret that contains
                        the Azure account access credentials.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    region:
                      description: Region specifies the Azure region where the cluster
                        will be created.
                      type: string
                  required:
                  - credentialsSecretRef
                  - region
                  type: object
                baremetal:
                  description: BareMetal is the configuration used when installing
                    on bare metal.
                  properties:
                    libvirtSSHPrivateKeySecretRef:
                      description: LibvirtSSHPrivateKeySecretRef is the reference
                        to the secret that contains the private SSH key to use for
                        access to the libvirt provisioning host. The SSH private key
                        is expected to be in the secret data under the "ssh-privatekey"
                        key.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                  required:
                  - libvirtSSHPrivateKeySecretRef
                  type: object
                gcp:
                  description: GCP is the configuration used when installing on Google
                    Cloud Platform.
                  properties:
                    credentialsSecretRef:
                      description: CredentialsSecretRef refers to a secret that contains
                        the GCP account access credentials.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    region:
                      description: Region specifies the GCP region where the cluster
                        will be created.
                      type: string
                  required:
                  - credentialsSecretRef
                  - region
                  type: object
                openstack:
                  description: OpenStack is the configuration used when installing
                    on OpenStack
                  properties:
                    cloud:
                      description: Cloud will be used to indicate the OS_CLOUD value
                        to use the right section from the cloud.yaml in the CredentialsSecretRef.
                      type: string
                    credentialsSecretRef:
                      description: CredentialsSecretRef refers to a secret that contains
                        the OpenStack account access credentials.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    trunkSupport:
                      description: TrunkSupport indicates whether or not to use trunk
                        ports in your OpenShift cluster.
                      type: boolean
                  required:
                  - cloud
                  - credentialsSecretRef
                  type: object
                vsphere:
                  description: VSphere is the configuration used when installing on
                    vSphere
                  properties:
                    certificatesSecretRef:
                      description: CertificatesSecretRef refers to a secret that contains
                        the vSphere CA certificates necessary for communicating with
                        the VCenter.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    cluster:
                      description: Cluster is the name of the cluster virtual machines
                        will be cloned into.
                      type: string
                    credentialsSecretRef:
                      description: 'CredentialsSecretRef refers to a secret that contains
                        the vSphere account access credentials: GOVC_USERNAME, GOVC_PASSWORD
                        fields.'
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    datacenter:
                      description: Datacenter is the name of the datacenter to use
                        in the vCenter.
                      type: string
                    defaultDatastore:
                      description: DefaultDatastore is the default datastore to use
                        for provisioning volumes.
                      type: string
                    folder:
                      description: Folder is the name of the folder that will be used
                        and/or created for virtual machines.
                      type: string
                    network:
                      description: Network specifies the name of the network to be
                        used by the cluster.
                      type: string
                    vCenter:
                      description: VCenter is the domain name or IP address of the
                        vCenter.
                      type: string
                  required:
                  - certificatesSecretRef
                  - credentialsSecretRef
                  - datacenter
                  - defaultDatastore
                  - vCenter
                  type: object
              type: object
            pullSecretRef:
              description: PullSecretRef is the reference to the secret to use when
                pulling images.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            size:
              description: Size is the default number of clusters that we should keep
                provisioned and waiting for use.
              type: integer
          required:
          - baseDomain
          - platform
          - size
          type: object
        status:
          description: ClusterPoolStatus defines the observed state of ClusterPool
          type: object
      required:
      - spec
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
