apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: clusterinstalls.hive.openshift.io
spec:
  group: hive.openshift.io
  names:
    kind: ClusterInstall
    listKind: ClusterInstallList
    plural: clusterinstalls
    singular: clusterinstall
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ClusterInstall represents a request to provision an agent based
        cluster.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ClusterInstallSpec defines the desired state of the Agent ClusterInstall.
          properties:
            imageSetRef:
              description: ImageSetRef is a reference to a ClusterImageSet. The release
                image specified in the ClusterImageSet will be used by clusters created
                for this cluster pool.
              properties:
                name:
                  description: Name is the name of the ClusterImageSet that this refers
                    to
                  type: string
              required:
              - name
              type: object
          required:
          - imageSetRef
          type: object
        status:
          description: ClusterInstallStatus defines the observed state of ClusterPool
          properties:
            conditions:
              description: Conditions includes more detailed status for the cluster
                install.
              items:
                description: ClusterInstallCondition contains details for the current
                  condition of a cluster install.
                properties:
                  lastProbeTime:
                    description: LastProbeTime is the last time we probed the condition.
                    format: date-time
                    type: string
                  lastTransitionTime:
                    description: LastTransitionTime is the last time the condition
                      transitioned from one status to another.
                    format: date-time
                    type: string
                  message:
                    description: Message is a human-readable message indicating details
                      about last transition.
                    type: string
                  reason:
                    description: Reason is a unique, one-word, CamelCase reason for
                      the condition's last transition.
                    type: string
                  status:
                    description: Status is the status of the condition.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
          type: object
      required:
      - spec
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
