apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: hiveconfigs.temphive.openshift.io
spec:
  group: temphive.openshift.io
  names:
    kind: HiveConfig
    plural: hiveconfigs
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalCertificateAuthorities:
              description: AdditionalCertificateAuthorities is a list of references
                to secrets in the 'hive' namespace that contain an additional Certificate
                Authority to use when communicating with target clusters. These certificate
                authorities will be used in addition to any self-signed CA generated
                by each cluster on installation.
              items:
                type: object
              type: array
            backup:
              description: Backup specifies configuration for backup integration.
                If absent, backup integration will be disabled.
              properties:
                minBackupPeriodSeconds:
                  description: MinBackupPeriodSeconds specifies that a minimum of
                    MinBackupPeriodSeconds will occur in between each backup. This
                    is used to rate limit backups. This potentially batches together
                    multiple changes into 1 backup. No backups will be lost as changes
                    that happen during this interval are queued up and will result
                    in a backup happening once the interval has been completed.
                  format: int64
                  type: integer
                velero:
                  description: Velero specifies configuration for the Velero backup
                    integration.
                  properties:
                    enabled:
                      description: Enabled dictates if Velero backup integration is
                        enabled. If not specified, the default is disabled.
                      type: boolean
                  type: object
              type: object
            externalDNS:
              description: ExternalDNS specifies configuration for external-dns if
                it is to be deployed by Hive. If absent, external-dns will not be
                deployed.
              properties:
                aws:
                  description: AWS contains AWS-specific settings for external DNS
                  properties:
                    credentials:
                      description: Credentials references a secret that will be used
                        to authenticate with AWS Route53. It will need permission
                        to manage entries in each of the managed domains for this
                        cluster. Secret should have AWS keys named 'aws_access_key_id'
                        and 'aws_secret_access_key'.
                      type: object
                  type: object
                gcp:
                  description: GCP contains GCP-specific settings for external DNS
                  properties:
                    credentials:
                      description: Credentials references a secret that will be used
                        to authenticate with GCP DNS. It will need permission to manage
                        entries in each of the managed domains for this cluster. Secret
                        should have a key names 'osServiceAccount.json'. The credentials
                        must specify the project to use.
                      type: object
                  type: object
              type: object
            failedProvisionConfig:
              description: FailedProvisionConfig is used to configure settings related
                to handling provision failures.
              properties:
                skipGatherLogs:
                  description: SkipGatherLogs disables functionality that attempts
                    to gather full logs from the cluster if an installation fails
                    for any reason. The logs will be stored in a persistent volume
                    for up to 7 days.
                  type: boolean
              type: object
            globalPullSecret:
              description: GlobalPullSecret is used to specify a pull secret that
                will be used globally by all of the cluster deployments. For each
                cluster deployment, the contents of GlobalPullSecret will be merged
                with the specific pull secret for a cluster deployment(if specified),
                with precedence given to the contents of the pull secret for the cluster
                deployment.
              type: object
            managedDomains:
              description: 'ManagedDomains is the list of DNS domains that are allowed
                to be used by the ''managedDNS'' feature. When specifying ''managedDNS:
                true'' in a ClusterDeployment, the ClusterDeployment''s baseDomain
                must be a direct child of one of these domains, otherwise the ClusterDeployment
                creation will result in a validation error.'
              items:
                type: string
              type: array
          type: object
        status:
          properties:
            aggregatorClientCAHash:
              description: AggregatorClientCAHash keeps an md5 hash of the aggregator
                client CA configmap data from the openshift-config-managed namespace.
                When the configmap changes, admission is redeployed.
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
