apiVersion: v1
kind: Template
metadata:
  name: cluster-deployment-template

parameters:
- name: CLUSTER_NAME
  displayName: Cluster Name
  description: The name to give to the Cluster created. If using real AWS, then this name should include your username so that resources created in AWS can be identified as yours.
  required: true
- name: ADMIN_EMAIL
  displayName: Admin Email
  description: Your email address.
  required: true
- name: ADMIN_PASSWORD
  displayName: Admin Password
  description: Your password to login to the new cluster.
  required: true
- name: SSH_KEY
  displayName: SSH Key
  description: Your public SSH key to reach instances.
  required: true
- name: BASE_DOMAIN
  displayName: Base DNS Domain
  description: Base DNS domain for your cluster. Will be combined with cluster name when creating entries.
  value: new-installer.openshift.com
- name: PULL_SECRET
  displayName: Pull Secret for OpenShift Images
  description: Pull Secret for OpenShift Images
  required: true
- name: AWS_ACCESS_KEY_ID
  required: true
  description: Base64 encoded AWS access key ID that can be used to provision cluster resources.
- name: AWS_SECRET_ACCESS_KEY
  required: true
  description: Base64 encoded AWS secret access key that can be used to provision cluster resources.
- name: HIVE_IMAGE
  displayName: Hive image URL
  description: Hive image URL
  value: "hive-controller:latest"
- name: HIVE_IMAGE_PULL_POLICY
  displayName: Hive image pull policy
  description: Hive image pull policy
  value: Never
- name: INSTALLER_IMAGE
  displayName: OpenShift Installer image URL
  description: OpenShift Installer image URL
  value: "registry.svc.ci.openshift.org/openshift/origin-v4.0:installer"
- name: INSTALLER_IMAGE_PULL_POLICY
  displayName: OpenShift Installer image pull policy
  description: OpenShift Installer image pull policy
  value: Always

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${CLUSTER_NAME}-aws-creds
  type: Opaque
  stringData:
    awsAccessKeyId: ${AWS_ACCESS_KEY_ID}
    awsSecretAccessKey: ${AWS_SECRET_ACCESS_KEY}

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${CLUSTER_NAME}-pull-secret
  type: kubernetes.io/dockercfg
  stringData:
    ".dockercfg": "${PULL_SECRET}"

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${CLUSTER_NAME}-ssh-key
  type: Opaque
  stringData:
    ssh-publickey: "${SSH_KEY}"

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${CLUSTER_NAME}-admin-creds
  type: Opaque
  stringData:
    password: ${ADMIN_PASSWORD}

- apiVersion: hive.openshift.io/v1alpha1
  kind: ClusterDeployment
  metadata:
    labels:
      controller-tools.k8s.io: "1.0"
    annotations:
      hive.openshift.io/delete-after: "8h"
    name: ${CLUSTER_NAME}
  spec:
    platformSecrets:
      aws:
        credentials:
          name: "${CLUSTER_NAME}-aws-creds"
    images:
      hiveImage: "${HIVE_IMAGE}"
      hiveImagePullPolicy: "${HIVE_IMAGE_PULL_POLICY}"
      installerImage: "${INSTALLER_IMAGE}"
      installerImagePullPolicy: "${INSTALLER_IMAGE_PULL_POLICY}"
    config:
      admin:
        email: ${ADMIN_EMAIL}
        password:
          name: "${CLUSTER_NAME}-admin-creds"
        sshKey:
          name: "${CLUSTER_NAME}-ssh-key"
      clusterID: ${CLUSTER_NAME} # TODO: what kind of ID is this
      baseDomain: ${BASE_DOMAIN}
      networking:
        type: OpenshiftSDN
        serviceCIDR: "172.30.0.0/16"
        podCIDR: "10.128.0.0/14"
      platform:
        aws:
          region: us-east-1
          vpcID: ""
          vpcCIDRBlock: 10.0.0.0/16
      pullSecret:
        name: "${CLUSTER_NAME}-pull-secret"
      machines:
      - name: master
        replicas: 3
        platform:
          aws:
            type: m4.large
            iamRoleName: ""
            rootVolume:
              iops: 100 # TODO
              size: 22
              type: gp2
      - name: worker
        replicas: 3
        platform:
          aws:
            type: m4.large
            iamRoleName: ""
            rootVolume:
              iops: 100 # TODO
              size: 22
              type: gp2

